# NUMPY

-- Numpy is a numerical python

In [ ]:
import numpy as np

In [ ]:
arr = np.array([])  # creating an empty array

In [ ]:
arr

In [ ]:
type(arr)

In [ ]:
arr.dtype

-- Properties of numpy
1. Homogenous -- all elements should be same data type.
2. Fixed Size - Once created the array size cannot change.
3. Mutable -- Values can be modified after creation.

In [ ]:
a = np.array([1,2,3,4,5,6])
print(a)

In [ ]:
a.dtype

In [ ]:
b = np.array([12.56,32.44,67.90])
print(b)
b.dtype

In [ ]:
c = np.array(['data',12.54,90])
print(c)
c.dtype

In [ ]:
# Fixed Size
d = np.array([100,200,300,400])
print(d)

In [ ]:
print("Memory ID: ",id(d))

In [ ]:
d=np.append(d,[1000,2000])
print(d)

In [ ]:
print("Memory ID: ",id(d))

In [ ]:
arr = np.array([1,2,3,4])
print(arr)

In [ ]:
arr.ndim     # to check the number of dimensions in the array

In [ ]:
arr.size    # size of an array/ num of items in a variable

In [ ]:
arr.shape   # shape of an array i.e., rows and columns

In [ ]:
arr1 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr1

In [ ]:
print(arr1.ndim)
print(arr1.shape)
print(arr1.size)

In [ ]:
arr2 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]])
arr2

In [ ]:
print(arr2.ndim)
print(arr2.shape)
print(arr2.size)

In [ ]:
# create a 5d matrix and its should have 3 depth
# create a 7d matrix with 0 depth

## BUILT - IN FUNCTIONS
### RESHAPE -- Changing shape of an array
-- converting 1D-2D-3D

In [ ]:
arr3 = np.array([100,200,300,400,500,600,700,800,900])
arr3

In [ ]:
arr4 = arr3.reshape(3,3)
arr4

In [ ]:
arr5 = np.array([1,2,4,5,6,12,13,14,15,16,23,24,25,26,33,34,35,36])
# convert it into 3d
# convert it into 4d with 2 depth

In [ ]:
arr6 = arr5.reshape([1,6,3])
arr6

In [ ]:
arr7 = arr6.reshape(1,2,3,3)
arr7

## ARANGE
-- Creating sequence with step values.

-- returns evenly spaced values within the interval.

In [ ]:
np.arange(25)

In [ ]:
np.arange(5,18)

In [ ]:
np.arange(0,20,2.3)

In [ ]:
#start - 23
#end - 678
#step - 55.5
np.arange(23,678,55.5)

In [ ]:
### Creating the arrays filled with Zero's and One's

In [ ]:
arr8 = np.zeros(5)
arr8

In [ ]:
arr9 = np.zeros((3,4),dtype=int)
arr9

In [ ]:
# create a 1-D array using ones function
# create a 3-D array using ones function and also change the datatype to int
arr10 = np.ones(8)
arr10

In [ ]:
arr10.ndim

In [ ]:
arr11= np.ones((3,3,2),dtype=int)
arr11

In [ ]:
arr11.ndim

## LINSPACE
-- Generating evenly spaced values

In [ ]:
np.linspace(2,20,15)

In [ ]:
np.linspace(0,100,45)

In [ ]:
arr = np.linspace(0,100,45)
print(arr)
print('step size :',step)

## EYE -- identity matrix
-- It generates an identity matrix, which is square matrix with 1's in diagonal
 and 0's everwhere else

In [ ]:
eye = np.eye(4)
eye

In [ ]:
eye1 = np.eye(4,5)
eye1

In [ ]:
eye2 = np.eye(4,5,k=1)
eye2

In [ ]:
eye3 = np.eye(6,7,k=-2)
eye3

In [ ]:
# create a identity matrix for 7*4 and k value is 1 also change dtype to int
eye4 = np.eye(7,4,dtype=int,k=1)
eye4

In [ ]:
# create an identity matrix where the diagonals should have 0's
     #rest of the places should have 1.

## BROADCASTING IN AN ARRAY
1. Broadcasting lets Numpy perform element wise operations on array of different shapes.
2. It automatically expands smaller arrays to match with larger one's.
3. This makes computation faster and more efficient without writing loops.

In [ ]:
a = [10,20,30,40,50]
b = 100

In [ ]:
result = []

In [ ]:
for x in a:
    result.append(x+b)
print(result)

In [ ]:
a_1 = np.array([10,20,30,40,50])
b_1 = 100

In [ ]:
print(a_1+b_1)

In [ ]:
a2 = np.array([[1],[2],[3]]) # (3,1)
b2 = np.array([10,20,30])    # (3,)
print(a2+b2)

## RANDOM NUMBER GENERATOR
1. Generating the random numbers with certain range.

   Functions-
   1. rand()
   2. randn()
   3. randint()

In [ ]:
# rand() -- uniform distribution (generates the random numbers in this range(0-1))
rand_1  = np.random.rand()
rand_1

In [ ]:
rand_2 = np.random.rand(3,4)
rand_2

In [ ]:
# randn() -- Generates the random numbers within the range of -3->+3, it uses standard normal distriburtion
rand_3 = np.random.randn()
rand_3

In [ ]:
rand_4 = np.random.randn(5,5)
rand_4

In [ ]:
# randint() -- generates the random integer
rand_5 = np.random.randint(2,20)
rand_5

In [ ]:
rand_7 = np.random.randint(1,50,20)
rand_7

In [ ]:
rand_6 = np.random.randint(10,50,(4,4))
rand_6

## STATISTICAL METHODS
1. MEAN
2. MEDIAN
3. MODE

In [ ]:
# Generate random integers in the range of 100-200 and also should be in 5*5 matrix
rand_8 = np.random.randint(100,200,(5,5))
rand_8

In [ ]:
print(np.mean(rand_8))
print(np.median(rand_8))
print(np.std(rand_8))

In [ ]:
## MIN/MAX
arr_9 = np.random.randint(100,500,20)
arr_9

In [ ]:
print(np.min(arr_9)) # returns the smallest number
print(np.max(arr_9)) # returns the largest number

In [ ]:
print(np.argmin(arr_9))  # returns the index location of smallest number
print(np.argmax(arr_9))  # returns the index location of largest number

# NUMPY INDEXING AND SLICING
-- Numpy provides powerful indexing techniques for selecting elements, filtering arrays and performing advanced operations efficiently.

In [ ]:
arr1 = np.arange(10,100,5)
arr1

In [ ]:
len(arr1)

In [ ]:
arr1[4]

In [ ]:
arr1[-6]

In [ ]:
arr1[4:9:3]

## FILTERING
-- Returns the values based on a condition.

In [ ]:
arr2 = np.array([1,2,1010,4,108,18,71,610])
arr2

In [ ]:
arr2<100

In [ ]:
np.where(arr2<100) # returns the index location where the condition is true

In [ ]:
arr2[np.where(arr2<100)] # returns the actual values that satisfies the condition

In [ ]:
arr3 = np.array([100,105,200,205,150,140,300,500,5000,1000,670,1000])
arr3

In [ ]:
arr3[np.where(arr3>500)]

In [ ]:
np.where(arr3>500)

In [ ]:
arr3[np.where(arr3==400)]=500  # changing values based on condition

In [ ]:
arr3

In [ ]:
# find the index location of all 400
np.where(arr3==400)

In [ ]:
## Indexing a 2D array
arr_2d = np.array([[1000,2000,3000],[4000,5000,6000],[7000,8000,9000]])
arr_2d

In [ ]:
print(arr_2d.ndim)
print(arr_2d.shape)
print(arr_2d.size)

In [ ]:
arr_2d

In [ ]:
arr_2d[1,1]

In [ ]:
arr_2d[1,2]

In [ ]:
arr_2d[2]

In [ ]:
arr_2d

In [ ]:
arr_2d[0:2,0:2]

In [ ]:
arr_2d[1:3,:]

In [ ]:
arr_2d[1:,:2]

## Indexing in a 3d- Array

In [ ]:
arr_3d = np.arange(27).reshape(3,3,3)
arr_3d

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
arr_3d[1,1,1]

13

In [ ]:
arr_3d[2,2,0]

24

In [ ]:
arr_3d[2,1:,1:]

array([[22, 23],
       [25, 26]])

## Fancy Indexing
-- Fancy indexing means accessing array elements using list of arrays of indices, instead
 of a single index or slice.

-- It helps in retrieving elements in any order and is useful do advanced selection.

In [ ]:
fan_arr = np.arange(100).reshape(10,10)
fan_arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [ ]:
fan_arr[[6,3,9,1]]  # fancy indexing on rows

array([[60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [ ]:
# fancy indexing on columns 2-92,5-95,7-97
fan_arr[:,[2,5,7]]

array([[ 2,  5,  7],
       [12, 15, 17],
       [22, 25, 27],
       [32, 35, 37],
       [42, 45, 47],
       [52, 55, 57],
       [62, 65, 67],
       [72, 75, 77],
       [82, 85, 87],
       [92, 95, 97]])